version: '3'
services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.1
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "9870:9870"
      - "8088:8088"
      - "8889:8888"
      - "7077:7077"
      - "16010:16010"
      - "8080:8080"
      - "9000:9000"
    volumes:
      - /home/moussa/Documents/S5/BigData/WeatherInsight-Analytics-End-to-End-BigData-Project/shared_volume/:/shared_volume
    expose:
      - "22"
    tty: true

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.1
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    networks:
      - hadoop
    ports:
      - "8040:8042"
    tty: true

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.1
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    networks:
      - hadoop
    ports:
      - "8041:8042"
    tty: true

networks:
  hadoop:
    driver: bridge
